name: macos
run-name: MacOS Workflow
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Environment
        run: make setup
      - name: Build ISO Image
        run: make all
